version: '3.3'

services:
  db:
    container_name: ${DB_NAME}
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: rootDBpwd_
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wp:
    container_name: ${SITENAME}
    depends_on:
      - db
    build: ./docker/wp
    image: giankd/wp
    ports:
      - '8080:80'
    restart: always
    env_file: ./.env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: ${DEBUG}
    volumes:
      - ./public:/var/www/html

volumes:
  db: {}
